# Generated by Django 3.1.8 on 2021-05-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.CharField(default='1234', max_length=50),
            preserve_default=False,
        ),
    ]
